# Generated by Django 5.0.4 on 2024-11-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(sql="CREATE EXTENSION IF NOT EXISTS pg_cron;"),
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION remove_exp_date() RETURNS INTEGER AS $$
                DECLARE
                    deleted_rows INTEGER := 0;
                BEGIN
                    deleted_rows := deleted_rows + (SELECT COUNT(*) FROM account_activation_code WHERE expires_at < NOW());
                    DELETE FROM account_activation_code WHERE expires_at < NOW();

                    deleted_rows := deleted_rows + (SELECT COUNT(*) FROM change_email_code WHERE expires_at < NOW());
                    DELETE FROM change_email_code WHERE expires_at < NOW();

                    deleted_rows := deleted_rows + (SELECT COUNT(*) FROM reset_password_code WHERE expires_at < NOW());
                    DELETE FROM reset_password_code WHERE expires_at < NOW();

                    deleted_rows := deleted_rows + (SELECT COUNT(*) FROM blacklist_token WHERE exp < NOW());
                    DELETE FROM blacklist_token WHERE exp < NOW();

                    deleted_rows := deleted_rows + (SELECT COUNT(*) FROM valid_token WHERE exp < NOW());
                    DELETE FROM valid_token WHERE exp < NOW();

                    return deleted_rows;
                END;
                $$ LANGUAGE plpgsql;
        """
        ),
        migrations.RunSQL(
            sql="""
                SELECT cron.schedule (
                    'remove_exp_date',
                    '0 3 * * *',
                    'SELECT remove_exp_date();'
                );
            """
        ),
    ]
