# Generated by Django 5.0.4 on 2024-12-10 15:10

from django.db import migrations
from user_app.periodic_tasks import create_periodic_task_for_expired_codes_removal


class Migration(migrations.Migration):
    """
    This migration creates a periodic task for the removal of expired codes.

    It uses the `create_periodic_task_for_expired_codes_removal` function to schedule
    the task that removes expired account activation codes, change email codes,
    and reset password codes from the database.
    """

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_periodic_task_for_expired_codes_removal)]
