# Generated by Django 5.0.4 on 2024-12-10 15:25

from django.db import migrations
from user_app.periodic_tasks import create_periodic_task_for_expired_tokens_removal


class Migration(migrations.Migration):
    """
    This migration creates a periodic task for the removal of expired tokens.

    It uses the `create_periodic_task_for_expired_tokens_removal` function to schedule
    the task that removes expired tokens from the
    `ValidTokenModel` and `BlacklistTokenModel` in the database.
    """

    dependencies = [
        ("user_app", "0002_task_remove_exp_code"),
    ]

    operations = [migrations.RunPython(create_periodic_task_for_expired_tokens_removal)]
