# Generated by Django 5.0.4 on 2025-02-17 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_task_remove_exp_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_reminder_at", models.DateTimeField()),
                ("second_reminder_at", models.DateTimeField()),
                ("activation_deadline", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Accounts",
                "db_table": "pending_accounts",
            },
        ),
    ]
