# Generated by Django 5.0.4 on 2025-02-21 00:58

from django.db import migrations
from user_app.periodic_tasks import (
    create_periodic_task_for_notify_first_reminder,
    create_periodic_task_for_notify_second_reminder,
)


class Migration(migrations.Migration):
    """
    This migration creates periodic tasks for activation reminders.

    It uses the `create_periodic_task_for_notify_first_reminder` and
    `create_periodic_task_for_notify_second_reminder` functions to schedule
    tasks that send activation reminder emails to users who have not yet
    activated their accounts.

    Tasks:
        - `task_notify_first_reminder`: Sends the first reminder email.
        - `task_notify_second_reminder`: Sends the second (final) reminder email.

    Schedule:
        - Frequency: Daily
        - Time: 9:00 AM
    """

    dependencies = [
        ("user_app", "0004_pendingaccounts"),
    ]

    operations = [
        migrations.RunPython(create_periodic_task_for_notify_first_reminder),
        migrations.RunPython(create_periodic_task_for_notify_second_reminder),
    ]
