"""
This module creates objects and dictionaries used to document HTTP responses and 
request data for the views. It defines response examples and data structures that 
will be included in the documentation generated by `drf-spectacular`.

The response examples and definitions help specify different success and error 
scenarios for the APIs, making it easier for developers and accounts of the API to 
understand the expected behavior of the endpoints.
"""

from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import OpenApiExample, OpenApiResponse
from user_app.constants.authentication import (
    AUTHORIZATION_HEADER_MISSING,
    AUTHORIZATION_HEADER_WITHOUT_BEARER,
    DECODE_ERROR,
    EXPIRED_SIGNATURE,
    INVALID_ALGORITHM,
    INVALID_AUTHORIZATION_HEADER_FORMAT,
    INVALID_SIGNATURE,
    INVALID_TOKEN,
    TOKEN_IN_BLACKLIST,
)

authentication_errors_response = OpenApiResponse(
    response=OpenApiTypes.OBJECT,
    description="Authentication Errors",
    examples=[
        OpenApiExample(
            "Authorization Header Missing",
            value={
                "code": "authentication_failed",
                "detail": AUTHORIZATION_HEADER_MISSING,
            },
        ),
        OpenApiExample(
            "Invalid Authorization Header Format",
            value={
                "code": "authentication_failed",
                "detail": INVALID_AUTHORIZATION_HEADER_FORMAT,
            },
        ),
        OpenApiExample(
            "Authorization Header Without 'Bearer'",
            value={
                "code": "authentication_failed",
                "detail": AUTHORIZATION_HEADER_WITHOUT_BEARER,
            },
        ),
        OpenApiExample("Token Decode Error", value=DECODE_ERROR),
        OpenApiExample("Invalid Token", value=INVALID_TOKEN),
        OpenApiExample("Invalid Signature", value=INVALID_SIGNATURE),
        OpenApiExample("Expired Signature", value=EXPIRED_SIGNATURE),
        OpenApiExample("Invalid Algorithm", value=INVALID_ALGORITHM),
        OpenApiExample("Token In Blacklist", value=TOKEN_IN_BLACKLIST),
    ],
)
