"""
This module creates objects and dictionaries used to document HTTP responses and 
request data for the views. It defines response examples and data structures that 
will be included in the documentation generated by `drf-spectacular`.

The response examples and definitions help specify different success and error 
scenarios for the APIs, making it easier for developers and accounts of the API to 
understand the expected behavior of the endpoints.
"""

from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import OpenApiExample, OpenApiResponse
from user_app.constants.http_response import (
    ACCOUNT_NOT_ACTIVATED,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_PASSWORD_RESET,
    CODE_EXPIRED,
    CODE_NOT_FOUND,
    EMAIL_SEND_TO_ACCOUNT_SUCCESSFULLY,
    VALIDATION_ERRORS,
)
from user_app.constants.validation_error_messages import (
    BLANK_FIELD,
    COMMON_PASSWORD,
    INVALID_FORMAT_EMAIL,
    NULL_FIELD,
    NUMERIC_PASSWORD,
    PASSWORD_DO_NOT_MATCH,
    REQUIRED_FIELD,
    SHORT_PASSWORD,
)

email_send_to_account_response = {
    "type": "object",
    "example": EMAIL_SEND_TO_ACCOUNT_SUCCESSFULLY,
}

email_validation_errors_response = {
    "type": "object",
    "example": {
        **VALIDATION_ERRORS,
        "field_errors": {
            "email": [
                INVALID_FORMAT_EMAIL,
                REQUIRED_FIELD,
                NULL_FIELD,
                BLANK_FIELD,
            ],
        },
    },
}

account_not_found_response = {
    "type": "object",
    "example": ACCOUNT_NOT_FOUND,
}

account_not_activated_response = {
    "type": "object",
    "example": ACCOUNT_NOT_ACTIVATED,
}

account_password_reset_response = {
    "type": "object",
    "example": {
        **ACCOUNT_PASSWORD_RESET,
        "access": "string jwt",
        "refresh": "string jwt",
    },
}

code_not_found_response = {
    "type": "object",
    "example": CODE_NOT_FOUND,
}

code_expired_response = {
    "type": "object",
    "example": CODE_EXPIRED,
}


passwords_validation_errors_response = OpenApiResponse(
    response=OpenApiTypes.OBJECT,
    description="Passwords Validation Errors",
    examples=[
        OpenApiExample(
            "Password Validation Errors",
            value={
                **VALIDATION_ERRORS,
                "field_errors": {
                    "password": [
                        SHORT_PASSWORD,
                        COMMON_PASSWORD,
                        NUMERIC_PASSWORD,
                        REQUIRED_FIELD,
                        NULL_FIELD,
                        BLANK_FIELD,
                    ],
                },
            },
        ),
        OpenApiExample(
            "Confirmation Password Validation Error",
            value={
                **VALIDATION_ERRORS,
                "field_errors": {
                    "confirmation_password": PASSWORD_DO_NOT_MATCH,
                },
            },
        ),
    ],
)
