# Dockerfile used to set up the runtime environment for a Django application with 
# Python 3.10 and Alpine 3.20.

# Set the base image as Python 3.10 on Alpine 3.20, a minimal operating system version
FROM python:3.10-alpine3.20

# Set environment variables to optimize Python behavior:
# - PYTHONDONTWRITEBYTECODE=1: Prevents creation of .pyc files
# - PYTHONUNBUFFERED=1: Disables Python output buffering
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Copy the requirements.txt file, containing Python dependencies, 
# to the /api working directory
COPY ./requirements.txt /api/

# Set the working directory where commands will be executed
WORKDIR /api/

# Expose port 8000 to allow access to the application via HTTP
EXPOSE 8000

# Create a virtual environment in the /venv directory,
# upgrade pip, and install the dependencies listed in requirements.txt
RUN python -m venv /venv && \
    /venv/bin/pip install --upgrade pip && \
    /venv/bin/pip install -r requirements.txt && \
    adduser --disabled-password djuser && \
    chown -R djuser:djuser /venv  && \
    mkdir -p /api/static && chown -R djuser:djuser /api/static

# Set the PATH to include the application scripts and the virtual environment
ENV PATH="/api/scripts:/venv/bin:$PATH"

USER djuser
