services:
  apiprod:
    container_name: apiprod
    build:
      context: ./../api/  
      dockerfile: ./../docker/Dockerfile.prod
    ports:
      - 8000:8000
    env_file:
      - ./../api/environments/.env.production
    command: ["sh", "-c", "chmod -R +x /api/scripts && commands.sh"]
    networks:
        - db_api
    depends_on:
      - psql

  psql:
    container_name: psql
    build:
      context: ./../api/  
      dockerfile: ./../docker/Dockerfile.prod-postgres
      args:
        DB_NAME: auth_db # set database name for Dockerfile.prod-postgres 
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./../api/environments/.env.production
    networks:
        - db_api

volumes:
  postgres_data:

networks:
  db_api:
    driver: bridge
