# docker-compose.yml used to set up the application services, including a Django server and a PostgreSQL database.

services:
  apidev:
    container_name: apidev  # Name of the container for the API service.
    build:
      context: ./../api/  
      dockerfile: ./../docker/Dockerfile.dev  
    ports:
      - 8000:8000  # Maps port 8000 of the container to port 8000 of the host.
    volumes:
      - ./../api/:/api  # Mounts the current directory to /api in the container for synchronization.
    env_file:
      - ./../api/environments/.env.development  # Development environment variables file.
    command: ["sh", "-c", "chmod -R +x /api/scripts && commands.sh"]  # Executes the command script with appropriate permissions.
    depends_on:
      - psql  # This service depends on the psql container.
    networks:
        - db_api

  psql:
    image: postgres:16-alpine
    container_name: psql  # Name of the container for the PostgreSQL service.
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # Mounts a persistent volume for PostgreSQL data.
    env_file:
      - ./../api/environments/.env.development  # Development environment variables file for PostgreSQL.
    ports:
      - 5432:5432  # Maps port 5432 of the container to port 5432 of the host.
    networks:
        - db_api

volumes:
  postgres_data:  # Persistent volume to store PostgreSQL data.

networks:
  db_api:
    driver: bridge

