services:
  psql:
    container_name: psql
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./../api/environments/.env
    networks:
      - db_api_net
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -d $POSTGRES_DB -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 2
  # ====================================
  redis_broker:
    container_name: redis_broker
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - redis_api_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 2
  # ====================================
  api:
    container_name: api
    build:
      context: ./../api/  
      dockerfile: ./../docker/Dockerfile.dev  
    volumes:
      - ./../api/:/api
    env_file:
      - ./../api/environments/.env
    command: ["sh", "-c", "commands.sh"]
    depends_on:
      psql:
        condition: service_healthy
      redis_broker:
        condition: service_healthy
    networks:
      - db_api_net
      - redis_api_net
      - nginx_network
    healthcheck:
      test: ["CMD", "sh", "-c", "grep -q 'MIGRATED=True' /home/djuser/my_environment"]
      interval: 10s
      timeout: 5s
      retries: 2
  # ====================================
  nginx:
    container_name: nginx
    build:
      context: ./../api/  
      dockerfile: ./../docker/Dockerfile.ngx 
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - nginx_network
  # ====================================
  # Celery Worker for 'removed_expired_code_token_queue'
  worker_removed_code_token:
    container_name: worker_removed_code_token
    build:
      context: ./../api/  
      dockerfile: ./../docker/Dockerfile.dev  
    command: ["sh", "-c", "celery -A config worker --loglevel=debug -Q remove_expired_code_token_queue"]
    volumes:
      - ./../api/:/api
    env_file:
      - ./../api/environments/.env
    depends_on:
      api:
        condition: service_healthy
    networks:
      - db_api_net
      - redis_api_net
    healthcheck:
      test: ["CMD", "celery", "-A", "config", "status"]
      interval: 10s
      timeout: 5s
      retries: 2
  # ====================================
  # Celery Worker for 'email_queue'
  worker_send_email:
    container_name: worker_send_email
    build:
      context: ./../api/
      dockerfile: ./../docker/Dockerfile.dev
    command: ["sh", "-c", "celery -A config worker --loglevel=debug -Q email_queue"]
    volumes:
      - ./../api/:/api
    env_file:
      - ./../api/environments/.env
    depends_on:
      api:
        condition: service_healthy
    networks:
      - db_api_net
      - redis_api_net
  # ====================================
  # Celery Beat for scheduling tasks
  celery_beat:
    container_name: celery_beat
    build:
      context: ./../api/  
      dockerfile: ./../docker/Dockerfile.dev  
    command: ["sh", "-c", "celery -A config beat --scheduler django --loglevel=debug"]
    volumes:
      - ./../api/:/api
    env_file:
      - ./../api/environments/.env
    depends_on:
      worker_removed_code_token:
        condition: service_healthy
    networks:
      - db_api_net
      - redis_api_net
# ====================================
volumes:
  postgres_data:
  redis_data:
# ====================================
networks:
  db_api_net:
    driver: bridge
  redis_api_net:
    driver: bridge
  nginx_network:
    driver: bridge
