services:
  apidev:
    container_name: apidev
    build:
      context: ./../api/  
      dockerfile: ./../docker/Dockerfile.dev  
    ports:
      - 8000:8000
    volumes:
      - ./../api/:/api
    env_file:
      - ./../api/environments/.env.development
    command: ["sh", "-c", "chmod -R +x /api/scripts && commands.sh"]
    depends_on:
      - psql
    networks:
        - db_api

  psql:
    container_name: psql
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./../api/environments/.env.development
    ports:
      - 5432:5432
    networks:
        - db_api

volumes:
  postgres_data:

networks:
  db_api:
    driver: bridge

