# Generated by Django 5.0.4 on 2024-09-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeEmailCodeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("old_email", models.EmailField(max_length=254)),
                ("new_email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "change email code",
                "db_table": "change_email_code",
            },
        ),
    ]
