# Generated by Django 5.0.4 on 2024-07-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomConfirmationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("confirmation_code", models.CharField(max_length=32, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type_code",
                    models.CharField(
                        choices=[
                            (
                                "registration_email_confirmation",
                                "Registration Email Confirmation",
                            ),
                            ("email_change_confirmation", "Email Change Confirmation"),
                            (
                                "password_change_confirmation",
                                "Password Change Confirmation",
                            ),
                            (
                                "password_reset_confirmation",
                                "Password Reset Confirmation",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
            ],
            options={
                "verbose_name": "Random Confirmation Code",
                "db_table": "random_confirmation_code",
            },
        ),
    ]
