# Generated by Django 5.0.4 on 2024-07-01 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_randomconfirmationcode"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RandomConfirmationCode",
            new_name="ConfirmationCode",
        ),
        migrations.AlterModelOptions(
            name="confirmationcode",
            options={"verbose_name": "Confirmation Code"},
        ),
        migrations.RenameField(
            model_name="confirmationcode",
            old_name="confirmation_code",
            new_name="code",
        ),
        migrations.AlterModelTable(
            name="confirmationcode",
            table="confirmation_code",
        ),
    ]
