# Generated by Django 5.0.4 on 2024-09-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_changeemailcodemodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="changeemailcodemodel",
            old_name="old_email",
            new_name="actual_email",
        ),
    ]
