# Generated by Django 5.0.4 on 2024-09-16 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_rename_old_email_changeemailcodemodel_actual_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountactivationcodemodel",
            name="user_email",
        ),
        migrations.AddField(
            model_name="accountactivationcodemodel",
            name="user",
            field=models.ForeignKey(
                db_column="user_email",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_activation_code",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
            preserve_default=False,
        ),
    ]
