# Generated by Django 5.0.4 on 2024-07-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_rename_randomconfirmationcode_confirmationcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JWTBlackList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.CharField(max_length=255)),
                ("exp", models.DateTimeField()),
                (
                    "typ",
                    models.CharField(
                        choices=[("access", "access"), ("refresh", "refresh")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="confirmationcode",
            name="type_code",
            field=models.CharField(
                choices=[
                    (
                        "account_activation",
                        "Registration Email Confirmation to account activation",
                    ),
                    ("email_change", "Email Change Confirmation"),
                    ("password_change", "Password Change Confirmation"),
                    ("password_reset", "Password Reset Confirmation"),
                ],
                max_length=64,
            ),
        ),
    ]
