# Generated by Django 5.0.4 on 2024-09-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_jwtblacklist_alter_confirmationcode_type_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountActivationCodeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("code", models.CharField(max_length=16, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "account activation code",
                "db_table": "account_activation_code",
            },
        ),
        migrations.DeleteModel(
            name="ConfirmationCode",
        ),
    ]
