# Generated by Django 5.0.4 on 2024-09-16 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_remove_accountactivationcodemodel_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changeemailcodemodel",
            name="actual_email",
        ),
        migrations.AddField(
            model_name="changeemailcodemodel",
            name="user",
            field=models.ForeignKey(
                db_column="old_user_email",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_email_code",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
            preserve_default=False,
        ),
    ]
