# Generated by Django 5.0.4 on 2024-09-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_accountactivationcodemodel_delete_confirmationcode"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JWTBlackList",
            new_name="JWTBlacklistModel",
        ),
        migrations.AlterField(
            model_name="accountactivationcodemodel",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
