# Generated by Django 5.0.4 on 2024-09-20 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_remove_changeemailcodemodel_actual_email_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JWTBlacklistModel",
            new_name="BlacklistTokenModel",
        ),
        migrations.AlterField(
            model_name="accountactivationcodemodel",
            name="user",
            field=models.ForeignKey(
                db_column="user_email",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_activation_codes",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
        migrations.AlterField(
            model_name="changeemailcodemodel",
            name="user",
            field=models.ForeignKey(
                db_column="old_user_email",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_email_codes",
                to=settings.AUTH_USER_MODEL,
                to_field="email",
            ),
        ),
    ]
