# Generated by Django 5.0.4 on 2024-09-20 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0006_rename_jwtblacklistmodel_blacklisttokenmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklisttokenmodel",
            name="user",
            field=models.ForeignKey(
                db_column="uid",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="black_list_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="RefreshTokenModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.CharField(max_length=255)),
                ("exp", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
