# Generated by Django 5.0.4 on 2024-09-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0007_blacklisttokenmodel_user_refreshtokenmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blacklisttokenmodel",
            options={"verbose_name": "blacklist token"},
        ),
        migrations.AlterModelOptions(
            name="refreshtokenmodel",
            options={"verbose_name": "refresh token"},
        ),
        migrations.AlterModelTable(
            name="blacklisttokenmodel",
            table="blacklist_token",
        ),
        migrations.AlterModelTable(
            name="refreshtokenmodel",
            table="refresh_token",
        ),
    ]
