# Generated by Django 5.0.4 on 2024-09-20 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0008_alter_blacklisttokenmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklisttokenmodel",
            name="user",
            field=models.ForeignKey(
                db_column="uid",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blacklist_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
