# Generated by Django 5.0.4 on 2024-10-01 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0009_alter_blacklisttokenmodel_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResetPasswordCodeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_email",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_password_codes",
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
            ],
            options={
                "verbose_name": "reset password code",
                "db_table": "reset_password_code",
            },
        ),
    ]
