# Generated by Django 5.0.4 on 2024-10-01 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0010_resetpasswordcodemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetpasswordcodemodel",
            name="code",
            field=models.CharField(default="defaultcode", max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resetpasswordcodemodel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 1, 19, 54, 28, 438270, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resetpasswordcodemodel",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 1, 19, 54, 37, 827213, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
