# Generated by Django 5.0.4 on 2024-10-02 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0011_resetpasswordcodemodel_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidTokenModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.CharField(max_length=255)),
                ("exp", models.DateTimeField()),
                (
                    "typ",
                    models.CharField(
                        choices=[("access", "access"), ("refresh", "refresh")],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valid_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "valid token",
                "db_table": "valid_token",
            },
        ),
        migrations.DeleteModel(
            name="RefreshTokenModel",
        ),
    ]
