"""
This module creates objects and dictionaries used to document HTTP responses and 
request data for the views. It defines response examples and data structures that 
will be included in the documentation generated by `drf-spectacular`.

The response examples and definitions help specify different success and error 
scenarios for the APIs, making it easier for developers and accounts of the API to 
understand the expected behavior of the endpoints.
"""

from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import OpenApiExample, OpenApiResponse
from account_auth.constants.http_response import (
    ACCOUNT_EMAIL_CHANGED,
    CODE_EXPIRED,
    CODE_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    EMAIL_ALREADY_IN_USE,
    EMAIL_SEND_TO_ACCOUNT_SUCCESSFULLY,
    VALIDATION_ERRORS,
)
from account_auth.constants.validation_error_messages import (
    BLANK_FIELD,
    EMAIL_ALREADY_EXISTS,
    INVALID_FORMAT_EMAIL,
    NULL_FIELD,
    REQUIRED_FIELD,
)

email_already_exists_response = {
    "type": "object",
    "example": EMAIL_ALREADY_EXISTS,
}

email_send_to_account_response = {
    "type": "object",
    "example": EMAIL_SEND_TO_ACCOUNT_SUCCESSFULLY,
}

email_validation_errors_and_email_already_in_use_response = OpenApiResponse(
    response=OpenApiTypes.OBJECT,
    description="Email Validation Errors or Email Already In Use",
    examples=[
        OpenApiExample(
            name="Email Already In Use",
            value=EMAIL_ALREADY_IN_USE,
        ),
        OpenApiExample(
            name="Email Validation Errors",
            value={
                **VALIDATION_ERRORS,
                "field_errors": {
                    "email": [
                        INVALID_FORMAT_EMAIL,
                        REQUIRED_FIELD,
                        NULL_FIELD,
                        BLANK_FIELD,
                    ],
                },
            },
        ),
    ],
)

change_email_request = {
    "application/json": {
        "type": "object",
        "example": {"code": "string code"},
    }
}

account_email_changed_response = {
    "type": "object",
    "example": {
        **ACCOUNT_EMAIL_CHANGED,
        "access": "string jwt",
        "refresh": "string jwt",
    },
}

code_not_found_response = {
    "type": "object",
    "example": CODE_NOT_FOUND,
}

code_expired_response = {
    "type": "object",
    "example": CODE_EXPIRED,
}
