"""
This module creates objects and dictionaries used to document HTTP responses and 
request data for the views. It defines response examples and data structures that 
will be included in the documentation generated by `drf-spectacular`.

The response examples and definitions help specify different success and error 
scenarios for the APIs, making it easier for developers and accounts of the API to 
understand the expected behavior of the endpoints.
"""

from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import OpenApiExample, OpenApiResponse
from account_auth.constants.authentication import (
    DECODE_ERROR,
    EXPIRED_SIGNATURE,
    INVALID_ALGORITHM,
    INVALID_SIGNATURE,
    INVALID_TOKEN,
    TOKEN_IN_BLACKLIST,
)
from account_auth.constants.http_response import (
    ACCOUNT_NOT_ACTIVATED,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_TOKEN_MISMATCH,
    IS_NOT_ACCESS_OR_REFRESH_TOKEN,
    IS_NOT_REFRESH_TOKEN,
    LOGIN_SUCCESSFUL,
    LOGOUT_SUCCESSFUL,
    TOKEN_ACCESS_CREATED,
    TOKEN_IS_VALID,
)

obtain_token_pair_request = {
    "application/json": {
        "type": "object",
        "example": {"email": "user@example.com", "password": "string"},
    }
}

account_not_found_response = {
    "type": "object",
    "example": ACCOUNT_NOT_FOUND,
}

account_not_activated_response = {
    "type": "object",
    "example": ACCOUNT_NOT_ACTIVATED,
}

login_successful_response = {
    "type": "object",
    "example": {
        **LOGIN_SUCCESSFUL,
        "access": "string jwt",
        "refresh": "string jwt",
    },
}

refresh_request = {
    "application/json": {
        "type": "object",
        "example": {"refresh": "string refresh token"},
    }
}

blacklist_token_and_account_not_activated = OpenApiResponse(
    response=OpenApiTypes.OBJECT,
    description="Token In Blacklist or Account Not Activated",
    examples=[
        OpenApiExample("Token In Blacklist", value=TOKEN_IN_BLACKLIST),
        OpenApiExample("Account Not Activated", value=ACCOUNT_NOT_ACTIVATED),
    ],
)

authentication_errors_response = OpenApiResponse(
    response=OpenApiTypes.OBJECT,
    description="Token Authentication Errors",
    examples=[
        OpenApiExample("Token decode error", value=DECODE_ERROR),
        OpenApiExample("Invalid token", value=INVALID_TOKEN),
        OpenApiExample("Invalid signature", value=INVALID_SIGNATURE),
        OpenApiExample("Expired signature", value=EXPIRED_SIGNATURE),
        OpenApiExample("Invalid algorithm", value=INVALID_ALGORITHM),
    ],
)

token_access_created_response = {
    "type": "object",
    "example": {
        **TOKEN_ACCESS_CREATED,
        "access": "string jwt",
    },
}

is_not_refresh_response = {
    "type": "object",
    "example": IS_NOT_REFRESH_TOKEN,
}


blacklist_token_and_account_token_mismatch = OpenApiResponse(
    response=OpenApiTypes.OBJECT,
    description="Token In Blacklist or Account Token Mismatch",
    examples=[
        OpenApiExample("Token In Blacklist", value=TOKEN_IN_BLACKLIST),
        OpenApiExample("Account Token Mismatch", value=ACCOUNT_TOKEN_MISMATCH),
    ],
)


blacklist_request = {
    "application/json": {
        "type": "object",
        "example": {"token": "string access_or_refresh_token"},
    }
}

logout_successful_response = {
    "type": "object",
    "example": LOGOUT_SUCCESSFUL,
}

is_not_access_or_refresh_response = {
    "type": "object",
    "example": IS_NOT_ACCESS_OR_REFRESH_TOKEN,
}

verify_token_request = {
    "application/json": {
        "type": "object",
        "example": {"token": "string access_or_refresh_token"},
    }
}

blacklist_response = {
    "type": "object",
    "example": TOKEN_IN_BLACKLIST,
}


token_is_valid_response = {
    "type": "object",
    "example": TOKEN_IS_VALID,
}
