[pytest]
DJANGO_SETTINGS_MODULE = config.settings
# Pattern to discover Python test files
python_files = test_*.py tests_*.py test.py tests.py
# Additional options for Pytest
# -s: Includes the output of print() in the test results
# -v: Makes the test output more verbose
addopts = -s -v

