[pytest]
DJANGO_SETTINGS_MODULE = config.settings
# Padrão de busca para arquivos de teste Python
python_files = test_*.py tests_*.py test.py tests.py
# Opções adicionais para o Pytest
# -s: Inclui a saída de print() na saída de resultados dos testes
# -v: Torna a saída dos testes mais verborrágica
addopts = -s -v